import mongoose from "mongoose";

/**
 * KnowledgeChunk stores one indexed text chunk from an uploaded document.
 *
 * The `embedding` field is a float32[768] vector generated by Gemini
 * text-embedding-004. This field is indexed in MongoDB Atlas with a
 * $vectorSearch index for ANN (Approximate Nearest Neighbor) retrieval.
 *
 * ATLAS VECTOR INDEX CONFIGURATION (create manually in Atlas UI or CLI):
 * -----------------------------------------------------------------------
 * Collection: knowledgechunks
 * Index name: knowledge_vector_index
 * Definition:
 * {
 *   "fields": [
 *     {
 *       "type": "vector",
 *       "path": "embedding",
 *       "numDimensions": 768,
 *       "similarity": "cosine"
 *     },
 *     {
 *       "type": "filter",
 *       "path": "userId"
 *     }
 *   ]
 * }
 * -----------------------------------------------------------------------
 *
 * SECURITY: Every $vectorSearch query MUST include filter: { userId }
 * to ensure users can only retrieve their own chunks.
 */
const knowledgeChunkSchema = new mongoose.Schema(
  {
    // CRITICAL: Always filter by userId in vector search queries (S-1)
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    sourceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "KnowledgeSource",
      required: true,
    },
    // The raw text content of this chunk (512-token window)
    text: {
      type: String,
      required: true,
    },
    // Gemini text-embedding-004 output: float32[768]
    // This is the vector used for semantic similarity search
    embedding: {
      type: [Number],
      required: true,
      // NOTE: Do NOT select this field in API responses — it's large (768 floats)
      // and exposing it is a security risk (S-7)
    },
    metadata: {
      pageNumber: { type: Number, default: 0 },
      chunkIndex: { type: Number, required: true },
      totalChunks: { type: Number, required: true },
      sourceFile: { type: String, required: true }, // "Q3 Report.pdf"
    },
  },
  {
    timestamps: { createdAt: true, updatedAt: false },
  }
);

// Fast bulk deletion when a source is removed (cascade pattern)
knowledgeChunkSchema.index({ sourceId: 1 });
// Fast user-scoped queries (used alongside Atlas vector filter)
knowledgeChunkSchema.index({ userId: 1 });

export const KnowledgeChunk = mongoose.model(
  "KnowledgeChunk",
  knowledgeChunkSchema
);
